name: remote ssh command
on: [push]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PROXY_KEY }}
        script: |
          ls -lha
          whoami
        # script: |
        #   sudo apt-get update -y
        #   sudo apt-get install build-essential -y
        #   scp -o StrictHostKeyChecking=no -r . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~
        #   cd ~
        #   make
        #   ./bin/program
